version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./.next:/app/.next
      - ./public:/app/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 